### PR TITLE
Updates to Lambda code for PEP8 uniformity

### PR DESCRIPTION
**Pull request by phillisf**
General syntax updates to bring parts of code into line with PEP8 formatting guidelines.

Also added some additional try / except to catch errors for each function.

Have set runtime to 3.6, though should also work in 2.7, but that is now deprecated.

### CODE REVIEW

**Comment by Manoj2087** [comment]
@phillisf the code change looks good. But have you had a chance to execute the lambda function under the runtime 3.6 ? i remember coming across some indentation issue when i tried to run under 3.6. Since I did not have much time to troubleshoot that I left it as 2.7

**Comment by phillisf** [comment]
@Manoj2087 let me deploy this tomorrow and check. I did some tests with a modified code version in Lambda but you're right; it would be better to test this solution from scratch.

**Comment by phillisf** [comment]
Tested and confirmed working in us-east-1 with Python 3.7 runtime.

**Comment by phillisf** [comment]
Merging based on @Manoj2087 's earlier comments and my testing.

**Pull request merged**
